  - name: Create build directory
    ansible.builtin.file:
      path: /tmp/docker/appserver
      state: directory
      mode: 0755
  - name: Copy dockerfile to builds directory
    template: src=./files/appserver.dockerfile dest=/tmp/docker/appserver/Dockerfile
  - name: Build an image
    ansible.builtin.shell: docker build -t tomcat /tmp/docker/appserver
  - name: Run container
    ansible.builtin.shell: docker run -dit --rm -p 8080:8080 tomcat
